"""test

Revision ID: 1f9733c3ba9d
Revises: b30ecb5f4462
Create Date: 2020-03-07 16:53:45.969814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9733c3ba9d'
down_revision = 'b30ecb5f4462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('msg', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'msg')
    # ### end Alembic commands ###
